### PR TITLE
collectd and CF231

### PR DESCRIPTION
**Pull request by LinuxBozo**
@sharms @dlapiduz Just for review, this is everything that would change now for prod..need to merge before "pushing the button"

### CODE REVIEW

**Comment by dlapiduz** [comment]
Is collectd sending all the data to riemann already for staging?

**Comment by dlapiduz** [comment]
How is it handling the traffic?

**Comment by sharms** [comment]
Riemann is not deployed in staging (yet), and the two scenarios:
1. If collectd is deployed and riemann is down, collectd will note the failure in the log and continue attempting.  No downside other than log messages generated each $interval
2. Riemann should be able to handle the traffic on our small instance the way it's configured, likely hundreds of additional data points and nodes before it becomes an issue.  Should Riemann not be able to handle the load, taking it down will interrupt InfluxDB data, however will not cause any other impact

**Comment by dlapiduz** [comment]
@sharms if collectd is not able to send the logs to riemann and continues to log stuff wouldn't it run out of hard drive?

**Comment by LinuxBozo** [comment]
@dlapiduz like any other job/package that produces logs inside a bosh vm, they would be rotated/compressed.

**Comment by sharms** [comment]
The current collectd is only using 98M of log space with several large periods of failures

**Comment by dlapiduz** [comment]
One more question: if collect all those logs and then try to push it to riemann at once, will collectd know ot to hammer riemann?

**Pull request merged**
