### PR TITLE
Add diego-stub

### PR DESCRIPTION
**Pull request by sushiandbeer**
Add required properties for diego integration.

### CODE REVIEW

**Comment by sharms** [comment]
Holding for example secrets file update and confirmation of staging secrets update

**Comment by sharms** [comment]
Any reason to not update East also?

**Comment by sushiandbeer** [comment]
We started with East, but moved Diego dev/testing to GovCloud as that’s where the Diego AWS resources were provisioned.  There’s no technical reason we can’t deploy Diego in E/W, but it seems that since we are shutting it down it’s good to focus on GovCloud.  I think it’s probably a matter of deciding if we want to continue to build out E/W

**Comment by sushiandbeer** [comment]
Even though we aren't deploying Diego there (yet?), I updated e/w secrets so the manifest generation doesn't break.

**Pull request merged**
