### PR TITLE
Update isolation segments

### PR DESCRIPTION
**Pull request by rogeruiz**
We have to be better about this. We haven't updated these files this calendar year yet, Diego Cell job configuration has changed a bunch since. We have to thoroughly test this in staging in order to verify that this is working as intended. :+1:

### CODE REVIEW

**Comment by mogul** [comment]
Can this can be made more DRY instead of requiring a recurring copy-pasta chore? Eg [like this](https://medium.com/@kinghuang/docker-compose-anchors-aliases-extensions-a1e4105d70bd)?

**Comment by rogeruiz** [comment]
The problem here is that when creating an isolation segment, we have to deploy more cells that are for that specific isolation. So unless they add multiple isolation segments upstream that we can then use BOSH interpolate `replace/remove` on, we have to copy and paste them ourselves. Since these cells just don't exist outside of the scope of a normal `cf-deployment.yml` file.

**Comment by rogeruiz** [comment]
And for optimizing what we copy over from the original manifest? I wouldn't suggest it because then it'll be even harder to see what we should change, add, or remove in the future when we change things. Basically the task comes down to having to understand the `diego-cell` instance-groups well enough to modify it by hand to support isolation segments. Meaning we'd need to have an isolation segment file like this for each and every isolation segment we want to provision, this is on top of providing extra routing on top of the configuration of the `diego-cell` instance groups.

**Comment by rogeruiz** [comment]
lastly, if you see the manifest file, you'll see there is already some yaml-anchors being used throughout the file. but we can't use a yaml anchor for the whole thing without then maintaining that `diego-cell` instance group section in the base manifest file too. and again, it'd make adding/removing things a real chore if we change it.

**Comment by mogul** [comment]
> this is on top of providing extra routing

I thought that the isolation segments as we are planning to deploy them for customers didn't have separate routing... Is that not the case?

All your explanation is understood! FWIW when I went looking around I found this [useful example of other anchor/injection methods for YAML](https://blog.daemonl.com/2016/02/yaml.html) which I didn't know about, and I bet are new to others too!

**Comment by mogul** [comment]
(I know we can't just make isolation-segments fully automatic... I guess what I was hoping for was just to make it possible to maintain one main stanza for "customer-facing isolation segment" and then just alias and reuse it for every other customer-facing isolation segment lower down in the same file, so we only have to update in one place to bring them all up to date in sync.)

**Comment by rogeruiz** [comment]
True, I mean I think we could do ourselves a favor and maintain a diego-cell stanza template which we then generate by plugging in the various differences like:

 ```yaml
values: 
        name: diego-*-cell
consumes:
        vpa: {from: vpa-*}
 provides:
        vpa: {as: vpa-*}
```

**Pull request merged**
