### PR TITLE
triggering smoke and acceptance tests after each deploy added

### PR DESCRIPTION
**Pull request by s-matyukevich**

### CODE REVIEW

**Comment by jmcarp** [comment]
@s-matyukevich: do we need the `semver` resource here? Could we use `get: cf-deployment-staging` instead and trigger on the bosh deployment directly?

**Comment by s-matyukevich** [comment]
@jmcarp 
As far as I know concourse no. From my understanding of concourse, there are only 2 options to trigger a job: run it manually or trigger it via resource change. In our case we need to trigger job automatically in case when no input resources for this job changed.  So this can be achieved only by adding additional resource, that will be changed each time when deploy-cf-staging job finishes successfully (that is exactly what I've done) or by adding additional resource, that will use fly cli to trigger the job manfully. 

If I am wrong and miss something: please provide me with the example or link to documentation that shows how can I trigger job in a different way.

**Comment by jmcarp** [comment]
So `cf-deployment-staging` is a bosh deployment resource, and the `deploy-cf-staging` job `put`s it, creating a new version of the resource. If the `smoke-tests-staging` job triggers on the `cf-deployment-staging` resource, then the smoke tests will run every time staging deploys. There's an example of a similar trigger here: https://github.com/18F/cg-deploy-admin-ui/blob/staging/ci/pipeline.yml#L55-L57. I think that should work for what you're doing here, but let me know if not.

**Comment by s-matyukevich** [comment]
@jmcarp 
ok got it, this is fixed here https://github.com/18F/cg-deploy-cf/pull/108

**Comment by s-matyukevich** [comment]
I just accidentally merged this pull request, that why I had to revert it and create new one https://github.com/18F/cg-deploy-cf/pull/108

**Pull request merged**
