### PR TITLE
Generate all the certificates in one directory

### PR DESCRIPTION
**Pull request by rogeruiz**
This script is currently a work in progress and is part of using a
single CA certificate to generate all the Cloud Foundry certificates we
need to deploy Cloud Foundry. Currently it's using a `master-bosh` cert.

We should finish up the script to pulling CA stuff done from Concourse or at
least put in the runbook that you need to download those files first and how.

Pairing with @wjwoodson.

### CODE REVIEW

**Comment by jmcarp** [comment]
Could we reuse the scripts in https://github.com/cloudfoundry/cf-release/tree/master/scripts?

**Comment by LinuxBozo** [comment]
@jmcarp Problem with those, they all have a tendency to generate their own CA cert.

**Comment by rogeruiz** [comment]
I'm going to wait to merge this in until after the rework around branches.

**Comment by rogeruiz** [comment]
Rebased and pointing to `master`. Should be good to merge now. It's been used now for migrating all five CF deployments 🥇

**Pull request merged**
