### PR TITLE
[WIP] Add a second dashboard client

### PR DESCRIPTION
**Pull request by jcscottiii**
### This PR is WIP until we get access to AWS creds again.

This client is for dashboard-staging, dashboard-demo and local dev

Long term, when creds are rotated, the creds will be pushed to the UPS
in the space of the app.

While it's easy to track the creds for the deployed apps in the UPS, it
would be complicated to maintain a separate env for local dev because
no app would be bound to it since it's local.
Now with the local dev as the same staging one, a dev could just read
the env of the staging app and get the creds.

### CODE REVIEW

**Comment by jmcarp** [comment]
Is it a good idea to give the staging dashboard admin access to production cloud.gov?

**Comment by rogeruiz** [comment]
@jmcarp we've discussed it a length 😕 The customer team's current workflow using production UAA for all integration steps. We're working on putting the pressure to help facilitate the transition. This is the first step. 

Thread: https://gsa-tts.slack.com/archives/C4XLJ1JBV/p1496240195190439

**Comment by jcscottiii** [comment]
on a related note: is it possible to for example create a client for only the CF staging env. (you see i added localhost:9999 in that dashboard-staging. i'm assuming that would be created in both envs though.)

**Comment by jmcarp** [comment]
Do you mean that adding a staging dashboard client to cloud.gov production is the first step toward moving the staging dashboard to cloud.gov staging? Not sure I understand--why not change the staging dashboard to deploy to cloud.gov staging and be done?

**Comment by jcscottiii** [comment]
I think the first step was to have it documented in this config (it exists but was manually created).

Also, I think the naming for everything may be confusing.

We can indeed move to do our master builds to deploy to fr-stage.cloud.gov
But we will need to have two separate apps still in CF prod.
Those two apps will be our:
- Production Dashboard
- Let's call it Integration Dashboard (formerly staging).

That integration dashboard is going to be needed to make sure that before we release, we have the same config and do sanity checks before releasing to production dashboard.
Now in terms of that being configured as two separate clients for as under one client with two `redirect_uri`s I'm up for either.

Ideally, we would have a way to make sure we allow localhost:9999 as a redirect_uri but only for staging CF. I'll admit, I messed up in this PR by putting that url in the redirect_uri for dashboard-staging since right now it'll be deployed to both environments as-is. [hence my question](https://github.com/18F/cg-deploy-cf/pull/234#issuecomment-306196874)

**Comment by jmcarp** [comment]
Closing this because it looks stale--we can reopen if necessary.

**Comment by pburkholder** [comment]
When James and I discussed this last week it seemed that running `dashboard.fr-stage.cloud.gov` sufficed for testing, so I don't think we'll need to re-open.

**Pull request closed without merging**
